"""Desktop launcher — generated by gs-app-pack.

Copy this file to your project root as app.py, then fill in the
SERVER STARTUP section.  Everything else is handled generically.

Supports three server modes (set in pack.config.ps1):
  function   -- calls module.func(host, port, cfg)
  uvicorn    -- calls uvicorn.run("module:app", host=host, port=port)
  subprocess -- spawns a shell command in a background process
"""
from __future__ import annotations

import argparse
import logging
import math
import socket
import struct
import subprocess
import sys
import threading
import time
from pathlib import Path

# ── PyInstaller bundle-path resolution ─────────────────────────────────────
if getattr(sys, "frozen", False):
    _BASE = Path(sys._MEIPASS)  # type: ignore[attr-defined]
else:
    _BASE = Path(__file__).resolve().parent

# ════════════════════════════════════════════════════════════════════════════
# TODO: patch module-level path constants that use __file__-relative paths.
# Add or remove lines as needed for your project.
# Example for gs-gh-summary:
#
#   import ghsummary.config as _cfg_mod; _cfg_mod.REPO_ROOT = _BASE
#   import server as _srv
#   _srv.REPO_ROOT = _BASE; _srv.STATIC_DIR = _BASE/"static"; _srv.TEMPLATES_DIR = _BASE/"templates"
#
# ════════════════════════════════════════════════════════════════════════════

log = logging.getLogger(__name__)

# ── CHANGE THESE to match your pack.config.ps1 ─────────────────────────────
_WIN_TITLE  = "My App"
_WIN_WIDTH  = 1400
_WIN_HEIGHT = 900
_WIN_BG     = "#07060a"

_DWM_CAPTION = 0x000A0607   # COLORREF 0x00BBGGRR for #07060a
_DWM_BORDER  = 0x0037AFD4   # #d4af37 gold
_DWM_TEXT    = 0x0095D1E8   # #e8d195 champagne

_ICON_BG   = "#07060a"
_ICON_RING = "#d4af37"
_ICON_SIZE = 32

_SERVER_HOST = "127.0.0.1"
_SERVER_PORT = 8790


# ════════════════════════════════════════════════════════════════════════════
# TODO: implement _start_server() for your project.
# This function is called in a daemon thread.
#
# Mode "function" example (gs-gh-summary):
#   from ghsummary import config as cfg_mod
#   import server as srv
#   def _start_server(host: str, port: int) -> None:
#       cfg = cfg_mod.load()
#       srv.serve(host, port, cfg)
#
# Mode "uvicorn" example (autogo):
#   import uvicorn
#   def _start_server(host: str, port: int) -> None:
#       uvicorn.run("web.app:app", host=host, port=port, log_level="warning")
#
# ════════════════════════════════════════════════════════════════════════════
def _start_server(host: str, port: int) -> None:
    raise NotImplementedError("Fill in _start_server() in app.py")


# ── icon generation ─────────────────────────────────────────────────────────

def _hex_to_bgra(hex_color: str) -> bytes:
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return bytes([b, g, r, 255])


def _make_icon_ico(size: int = 32, bg: str = "#07060a", ring: str = "#d4af37") -> bytes:
    BG   = _hex_to_bgra(bg)
    GOLD = _hex_to_bgra(ring)
    cx = cy = (size - 1) / 2.0
    r_outer, r_inner = size * 0.42, size * 0.22

    def lerp4(a: bytes, b: bytes, t: float) -> bytes:
        t = max(0.0, min(1.0, t))
        return bytes(int(a[i] + (b[i] - a[i]) * t) for i in range(4))

    rows = []
    for y in range(size - 1, -1, -1):
        row = bytearray()
        for x in range(size):
            d = math.hypot(x - cx, y - cy)
            if   d <= r_inner - 0.5: row += BG
            elif d <= r_inner + 0.5: row += lerp4(BG, GOLD, d - (r_inner - 0.5))
            elif d <= r_outer - 0.5: row += GOLD
            elif d <= r_outer + 0.5: row += lerp4(GOLD, BG, d - (r_outer - 0.5))
            else:                    row += BG
        rows.append(bytes(row))

    pixel_data = b"".join(rows)
    and_mask   = bytes(((size + 31) // 32 * 4) * size)
    bih        = struct.pack("<IIIHHIIIIII", 40, size, size * 2, 1, 32, 0, 0, 0, 0, 0, 0)
    image_data = bih + pixel_data + and_mask
    ico_header = struct.pack("<HHH", 0, 1, 1)
    dir_entry  = struct.pack("<BBBBHHII", size, size, 0, 0, 1, 32, len(image_data), 22)
    return ico_header + dir_entry + image_data


def _ensure_icon() -> Path | None:
    p = _BASE / "static" / "gs-icon.ico"
    if not p.exists():
        try:
            p.write_bytes(_make_icon_ico(_ICON_SIZE, _ICON_BG, _ICON_RING))
        except Exception as exc:
            log.warning("icon generation failed: %s", exc)
            return None
    return p


# ── Windows DWM styling ─────────────────────────────────────────────────────

def _apply_win32_style(icon_path: Path | None) -> None:
    if sys.platform != "win32":
        return
    try:
        import ctypes
        hwnd = 0
        deadline = time.monotonic() + 5.0
        while not hwnd and time.monotonic() < deadline:
            hwnd = ctypes.windll.user32.FindWindowW(None, _WIN_TITLE)
            if not hwnd:
                time.sleep(0.1)
        if not hwnd:
            return

        DWMWA_BORDER_COLOR  = 34
        DWMWA_CAPTION_COLOR = 35
        DWMWA_TEXT_COLOR    = 36

        def _dwm(attr: int, colorref: int) -> None:
            v = ctypes.c_int(colorref)
            ctypes.windll.dwmapi.DwmSetWindowAttribute(
                hwnd, attr, ctypes.byref(v), ctypes.sizeof(v))

        _dwm(DWMWA_CAPTION_COLOR, _DWM_CAPTION)
        _dwm(DWMWA_BORDER_COLOR,  _DWM_BORDER)
        _dwm(DWMWA_TEXT_COLOR,    _DWM_TEXT)

        if icon_path and icon_path.exists():
            LR_LOADFROMFILE, IMAGE_ICON, WM_SETICON = 0x10, 1, 0x80
            for sz, kind in ((32, 1), (16, 0)):
                hicon = ctypes.windll.user32.LoadImageW(
                    None, str(icon_path), IMAGE_ICON, sz, sz, LR_LOADFROMFILE)
                if hicon:
                    ctypes.windll.user32.SendMessageW(hwnd, WM_SETICON, kind, hicon)
    except Exception as exc:
        log.warning("win32 styling failed: %s", exc)


# ── server helpers ──────────────────────────────────────────────────────────

def _port_is_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) != 0


def _find_free_port(preferred: int) -> int:
    if _port_is_free(preferred):
        return preferred
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _wait_for_server(port: int, timeout: float = 15.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.5):
                return True
        except OSError:
            time.sleep(0.1)
    return False


# ── entry point ──────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--port", type=int, default=_SERVER_PORT)
    args = p.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s -- %(message)s",
        datefmt="%H:%M:%S",
    )

    port = _find_free_port(args.port)
    threading.Thread(
        target=_start_server, args=(_SERVER_HOST, port),
        daemon=True, name="app-server",
    ).start()

    if not _wait_for_server(port):
        log.error("server did not start within 15 s")
        return 1

    icon_path = _ensure_icon()
    url = f"http://{_SERVER_HOST}:{port}/"
    log.info("server ready at %s", url)

    try:
        import webview
    except ImportError:
        log.error("pywebview not installed -- run: pip install pywebview")
        return 1

    webview.create_window(
        _WIN_TITLE, url,
        width=_WIN_WIDTH, height=_WIN_HEIGHT,
        resizable=True, min_size=(800, 600),
        background_color=_WIN_BG,
    )
    webview.start(func=lambda: _apply_win32_style(icon_path), debug=False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
